version: "3.3"

services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
